apiVersion: v1
kind: Service
metadata:
  name: llm-service
spec:
  # type: LoadBalancer
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: llm-server
