kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
    name: llm-http-scaling
spec:
    hosts: 
      - llm-service
    scaleTargetRef:
        name: llm-deployment
        kind: Deployment
        apiVersion: apps/v1
        service: llm-service
        port: 8000
    replicas:
        min: 0
        max: 10
    scaledownPeriod: 30
    scalingMetric:
        requestRate:
            granularity: 1s
            targetValue: 5
            window: 10s

