apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gemma-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: tgi-gemma-deployment
    kind: Deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metric:
        name: prometheus.googleapis.com|tgi_queue_size|gauge
      target:
        type: AverageValue
        averageValue: "5" # Target average queue size
