apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: vllmmonitor
  labels:
    app.kubernetes.io/name: vllmmonitor
    app.kubernetes.io/part-of: google-cloud-managed-prometheus
spec:
  selector:
    matchLabels:
      app: gemma3-server

  endpoints:
  - port: 8000 
    path: /metrics
    interval: 15s
---
apiVersion: monitoring.googleapis.com/v1
kind: OperatorConfig
metadata:
  namespace: gmp-public
  name: config
features:
  targetStatus:
    enabled: true
