apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  annotations:
    aire.gke.io/generated: "true"
  labels:
    app.kubernetes.io/name: tgi
    app.kubernetes.io/part-of: google-cloud-managed-prometheus
  name: gemma-podmonitoring
  namespace: default
spec:
  endpoints:
  - port: 8000
    scheme: http
    interval: 15s
    path: /metrics
  selector:
    matchLabels:
      app: gemma-inference-server
