kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
    name: nginx-scaledobject
spec:
    hosts:
        - 34.67.199.151
    scaleTargetRef:
        name: nginx-deployment
        kind: Deployment
        apiVersion: apps/v1
        service: nginx-service
        port: 80
    replicas:
        min: 0
        max: 10
    scaledownPeriod: 10

    scalingMetric:
        requestRate:
            granularity: 1s
            targetValue: 1
            window: 5s
